version: "3.9"
services:
  db:
    image: mongo:5-focal
    restart: always
    volumes:
      - mongo:/data/db
  api:
    build: ./bookclub-api
    environment:
      - MONGODB=mongodb://db
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
  client:
    build: ./bookclub-client
    restart: always
    depends_on:
      - api
    ports:
      - "3000:3000"
volumes:
  mongo:
