[package]
name = "bookclub-api"
version = "0.1.0"
authors = ["Martin Disch <martindisch@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "3.3.2"
env_logger = "0.8.2"
mongodb = "1.1.1"
dotenv = "0.15.0"
bson = "1.1.0"
serde = "1.0.121"
